language: generic 
sudo:required
services:
    - docker 

before_install:
    - docker build -t nathant27/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true nathant27/docker-react npm run test